# Generated by Django 4.2.11 on 2024-04-22 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='')),
                ('rated', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('assertiveness', models.IntegerField(default=0)),
                ('enthusiasm', models.IntegerField(default=0)),
                ('clairity', models.IntegerField(default=0)),
                ('engagement', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clips', models.ManyToManyField(to='app.clip')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
