# Generated by Django 5.0.4 on 2024-05-06 03:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_clip_clipold_remove_profile_clips_clipnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('clip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('audio', models.FileField(upload_to='')),
                ('rated', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('assertiveness', models.IntegerField(default=0)),
                ('enthusiasm', models.IntegerField(default=0)),
                ('clairity', models.IntegerField(default=0)),
                ('engagement', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='app.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='clipnew',
            name='profile',
        ),
        migrations.DeleteModel(
            name='clipOld',
        ),
        migrations.DeleteModel(
            name='clipNew',
        ),
    ]
